[package]
name = "mediatoascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
derive_builder = "0.11.2"
image = "0.24.3"
imageproc = "0.23.0"
indicatif = "0.17.1"
once_cell = "1.14.0"
opencv = "0.68.0"
rusttype = "0.9.2"
